name: Linux Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    container:
      image: lighterowl/transgui-sdk:1.0
      credentials:
        username: lighterowl
        password: ${{ secrets.DOCKER_HUB_PAT }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - run: .github/build_linux.sh

    - uses: actions/upload-artifact@v4
      with:
        name: TransGUI Linux
        path: units/transgui-x86_64.AppImage
        if-no-files-found: error
