name: macOS Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-macos-arm64:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - run: .github/build_macos.sh

    - uses: actions/upload-artifact@v3
      with:
        name: TransGUI macOS arm64
        path: transgui_ppca64

  build-macos-x64:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - uses: actions/cache@v3
      with:
        path: |
          ~/.transgui_sdk/lazarus
          ~/.transgui_sdk/fpc-3.2.3
        key: macos-fpc-lazarus

    - run: .github/build_macos.sh

    - uses: actions/download-artifact@v3
      with:
        name: TransGUI macOS arm64
        path: transgui_ppca64

    - run: .github/package_macos.sh

# keeping this around would just be confusing
    - uses: geekyeggo/delete-artifact@v2
      with:
        name: TransGUI macOS arm64

    - uses: actions/upload-artifact@v3
      with:
        name: TransGUI macOS Universal Binary
        path: Release/transgui.dmg
